### ISSUE TITLE
Broken code in v2.1.1

### ISSUE THREAD

**Issue by glenswift** [gregwebs/redux-side-effect#3]
ES2015 modules haven't been compiled in v2.1.1.

To reproduce issue you should `npm install redux-side-effects` and confirm that there are `export` statements in `./lib/index.js`.

I've renamed `prepublish` to `build` and everything seems to be working fine:

```
git clone git@github.com:gregwebs/redux-side-effect.git
cd redux-side-effect
npm install
npm run-script build
```

so I don't know what the problem is. It's probably something with your local babel setup or something.

**Comment by gregwebs** [comment]
yeah, was a problem with the newer babel version not working

**Comment by gregwebs** [comment]
2.1.2 is published now, looks better

**Comment by glenswift** [comment]
It works now. Thanks!
